version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/currencydb
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/java/Databases/up.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
